name: 'Dependency Cruiser Action'
description: 'Report dependency-cruiser results'
author: 'Victor Chabbert'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  github_token:
    required: true
    description: "A github access token"
  input:
    required: true
    description: "An unordered list of files or folders to cruise. See dependency-cruiser for the available options"
  config:
    required: true
    description: 'Path from the git root to the dependency cruise file'
    default: ".dependency-cruiser.js"
  failOn:
    required: false
    description: 'Severity condition the action should fail on. Possible values: error, warn, info, none'
    default: 'error'
  skipInstall:
    required: false
    description: "Skip the package installation for the PR branch"
  installDirectory:
    required: false
    description: "The path pointing to the package.json"
  diff:
    required: false
    description: 'Compare the summary between the PR branch and the target branch'
